---
name: Stack Project Starter
version: 0.1

requires: 
  - npm
  - git

start:
  - npm run dev

install:
  - git clone https://github.com/ajhenry/stack.git .
  - yarn
  - yarn prepack

postinstall:
  - yarn link
  - message: To use the CLI, you can use the stack command